version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - npm install yarn -g
    - /opt/elasticbeanstalk/bin/get-config environment | jq -r 'to_entries | .[] | "export \(.key)=\"\(.value)\""' > /etc/profile.d/sh.local
artifacts:
  type: zip
  files: 
    - server/package.json
    - server/yarn.lock
    - 'server/dist/**/*'
    - Dockerfile
    - Dockerrun.aws.json