version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
    - npm install yarn -g
artifacts:
  type: zip
  files: 
    - server/package.json
    - server/yarn.lock
    - 'server/dist/**/*'
    - Dockerfile
    - Dockerrun.aws.json