version: '3'

services:
  mongo:
    build: ./mongo/
    ports:
      - "27017:27017"
  server:
    build: .
    ports:
      - '9090:9090'
    volumes:
      - ./app/:/app/
      - /app/node_modules/
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/bash -c "yarn && yarn start"