version: '3'

services:
  mongo:
    build: ./mongo/
    ports:
      - "27017:27017"
  server:
    build: ./server/
    ports:
      - '9090:9090
      - '80:80'
    volumes:
      - ./server/:/server/
      - /app/node_modules/
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/bash -c "yarn && yarn start"